
[build]
  publish = "dist"
  command = "npm run build"

[build.processing]
  skip_processing = false
  
[build.processing.html]
  pretty_urls = true

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true
  bundle = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/feed.xml"
  [headers.values]
    Content-Type = "application/rss+xml; charset=UTF-8"
    Cache-Control = "public, max-age=3600"

# Redirections pour corriger les erreurs 404 détectées par Google Search Console
[[redirects]]
  from = "/author/*/feed/*"
  to = "/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/category/*/feed/*"
  to = "/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/feed/"
  to = "/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/*/feed/"
  to = "/feed.xml"
  status = 301
  force = true

# Redirection générale pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
